/*====================================================
EXERCISE 5 : TRIGGERS

A trigger is a PL/SQL block that automatically executes when an INSERT, UPDATE or DELETE operation occurs on a
table.

Advantages of Triggers:
1. Maintains data integrity.
2. Automatically updates data.
3. Provides auditing facilities.
4. Enforces business rules.
====================================================*/


/*====================================================
Scenario 1:
Update LastModified whenever a customer record is updated.
====================================================*/

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/




/*====================================================
Scenario 2:
Maintain an audit log for transactions.
====================================================*/

/* Create AuditLog table */

CREATE TABLE AuditLog(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    VALUES(
        DEFAULT,
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        SYSDATE
    );
END;
/




/*====================================================
Scenario 3:
Check transaction rules before inserting.
====================================================*/

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN
    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal' THEN
        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'Insufficient Balance'
            );
        END IF;
    END IF;

    IF :NEW.TransactionType = 'Deposit' THEN
        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(
                -20002,
                'Deposit amount must be positive'
            );
        END IF;
    END IF;
END;
/